apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sy16-task3
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
